allowBuilds:
  '@prisma/engines': false
  prisma: false
  sharp: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@img/sharp-darwin-arm64@0.35.1'
  - '@img/sharp-darwin-x64@0.35.1'
  - '@img/sharp-freebsd-wasm32@0.35.1'
  - '@img/sharp-linux-arm64@0.35.1'
  - '@img/sharp-linux-arm@0.35.1'
  - '@img/sharp-linux-ppc64@0.35.1'
  - '@img/sharp-linux-riscv64@0.35.1'
  - '@img/sharp-linux-s390x@0.35.1'
  - '@img/sharp-linux-x64@0.35.1'
  - '@img/sharp-linuxmusl-arm64@0.35.1'
  - '@img/sharp-linuxmusl-x64@0.35.1'
  - '@img/sharp-wasm32@0.35.1'
  - '@img/sharp-webcontainers-wasm32@0.35.1'
  - '@img/sharp-win32-arm64@0.35.1'
  - '@img/sharp-win32-ia32@0.35.1'
  - '@img/sharp-win32-x64@0.35.1'
  - sharp@0.35.1
overrides:
  '@types/pg': 8.20.0
  svgo: '>=3.3.3'
  picomatch: '>=4.0.4'
  postcss: '>=8.5.10'
  hono: '>=4.12.21'
  '@hono/node-server': '>=1.19.13'
  '@babel/plugin-transform-modules-systemjs': '>=7.29.4'
publicHoistPattern:
  - '*jest*'
  - '*@jest/*'
