import { DISCOGS_OAUTH_TEST_ENV } from "../src/tests/discogsOAuthTestEnv";

process.env.ENVIRONMENT = "staging";
process.env.DISCOGS_CONSUMER_KEY = DISCOGS_OAUTH_TEST_ENV.DISCOGS_CONSUMER_KEY;
process.env.DISCOGS_CONSUMER_SECRET =
  DISCOGS_OAUTH_TEST_ENV.DISCOGS_CONSUMER_SECRET;
