// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'89f0302d27aa0cb758f4042ba676e4498035d3f551ca6d57062faa1260ea5ed4'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly CrateReleases: {
      readonly userId: CodecTypes['pg/int4@1']['output'];
      readonly crateId: CodecTypes['pg/text@1']['output'];
      readonly instanceId: CodecTypes['pg/text@1']['output'];
      readonly releaseData: CodecTypes['pg/jsonb@1']['output'];
      readonly addedAt: TimestampString<3>;
      readonly foundAt: TimestampString<3> | null;
      readonly sortOrder: CodecTypes['pg/int4@1']['output'];
    };
    readonly Crates: {
      readonly userId: CodecTypes['pg/int4@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly isDefault: CodecTypes['pg/bool@1']['output'];
      readonly createdAt: TimestampString<3>;
      readonly updatedAt: TimestampString<3>;
      readonly private: CodecTypes['pg/bool@1']['output'];
      readonly username: CodecTypes['pg/text@1']['output'] | null;
      readonly packedEnabled: CodecTypes['pg/bool@1']['output'];
      readonly notes: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly CrateSetMarkers: {
      readonly userId: CodecTypes['pg/int4@1']['output'];
      readonly crateId: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly label: CodecTypes['pg/text@1']['output'];
      readonly sortOrder: CodecTypes['pg/int4@1']['output'];
      readonly createdAt: TimestampString<3>;
      readonly updatedAt: TimestampString<3>;
    };
    readonly PrismaMigrations: {
      readonly id: Varchar<36>;
      readonly checksum: Varchar<64>;
      readonly finishedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly migrationName: Varchar<255>;
      readonly logs: CodecTypes['pg/text@1']['output'] | null;
      readonly rolledBackAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly startedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly appliedStepsCount: CodecTypes['pg/int4@1']['output'];
    };
    readonly ProductAnalyticsDailyRollups: {
      readonly date: CodecTypes['pg/date-string@1']['output'];
      readonly dimensionType: CodecTypes['pg/text@1']['output'];
      readonly dimensionKey: CodecTypes['pg/text@1']['output'];
      readonly eventCount: CodecTypes['pg/int4@1']['output'];
    };
    readonly ProductAnalyticsEvents: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly event: CodecTypes['pg/text@1']['output'];
      readonly category: CodecTypes['pg/text@1']['output'];
      readonly action: CodecTypes['pg/text@1']['output'];
      readonly label: CodecTypes['pg/text@1']['output'];
      readonly value: CodecTypes['pg/text@1']['output'] | null;
      readonly pagePath: CodecTypes['pg/text@1']['output'] | null;
      readonly userId: CodecTypes['pg/int4@1']['output'] | null;
      readonly createdAt: TimestampString<3>;
    };
    readonly Users: {
      readonly discogsUserId: CodecTypes['pg/int4@1']['output'];
      readonly username: CodecTypes['pg/text@1']['output'];
      readonly createdAt: TimestampString<3>;
      readonly updatedAt: TimestampString<3>;
      readonly preferences: CodecTypes['pg/jsonb@1']['output'];
      readonly loginCount: CodecTypes['pg/int4@1']['output'];
      readonly supportToastDismissed: CodecTypes['pg/bool@1']['output'];
      readonly supportToastPending: CodecTypes['pg/bool@1']['output'];
      readonly lastSeenAt: TimestampString<3> | null;
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly CrateReleases: {
      readonly userId: CodecTypes['pg/int4@1']['input'];
      readonly crateId: CodecTypes['pg/text@1']['input'];
      readonly instanceId: CodecTypes['pg/text@1']['input'];
      readonly releaseData: CodecTypes['pg/jsonb@1']['input'];
      readonly addedAt: CodecTypes['pg/timestamp-string@1']['input'];
      readonly foundAt: CodecTypes['pg/timestamp-string@1']['input'] | null;
      readonly sortOrder: CodecTypes['pg/int4@1']['input'];
    };
    readonly Crates: {
      readonly userId: CodecTypes['pg/int4@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly isDefault: CodecTypes['pg/bool@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamp-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamp-string@1']['input'];
      readonly private: CodecTypes['pg/bool@1']['input'];
      readonly username: CodecTypes['pg/text@1']['input'] | null;
      readonly packedEnabled: CodecTypes['pg/bool@1']['input'];
      readonly notes: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly CrateSetMarkers: {
      readonly userId: CodecTypes['pg/int4@1']['input'];
      readonly crateId: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly label: CodecTypes['pg/text@1']['input'];
      readonly sortOrder: CodecTypes['pg/int4@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamp-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamp-string@1']['input'];
    };
    readonly PrismaMigrations: {
      readonly id: CodecTypes['sql/varchar@1']['input'];
      readonly checksum: CodecTypes['sql/varchar@1']['input'];
      readonly finishedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly migrationName: CodecTypes['sql/varchar@1']['input'];
      readonly logs: CodecTypes['pg/text@1']['input'] | null;
      readonly rolledBackAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly startedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly appliedStepsCount: CodecTypes['pg/int4@1']['input'];
    };
    readonly ProductAnalyticsDailyRollups: {
      readonly date: CodecTypes['pg/date-string@1']['input'];
      readonly dimensionType: CodecTypes['pg/text@1']['input'];
      readonly dimensionKey: CodecTypes['pg/text@1']['input'];
      readonly eventCount: CodecTypes['pg/int4@1']['input'];
    };
    readonly ProductAnalyticsEvents: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly event: CodecTypes['pg/text@1']['input'];
      readonly category: CodecTypes['pg/text@1']['input'];
      readonly action: CodecTypes['pg/text@1']['input'];
      readonly label: CodecTypes['pg/text@1']['input'];
      readonly value: CodecTypes['pg/text@1']['input'] | null;
      readonly pagePath: CodecTypes['pg/text@1']['input'] | null;
      readonly userId: CodecTypes['pg/int4@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamp-string@1']['input'];
    };
    readonly Users: {
      readonly discogsUserId: CodecTypes['pg/int4@1']['input'];
      readonly username: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamp-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamp-string@1']['input'];
      readonly preferences: CodecTypes['pg/jsonb@1']['input'];
      readonly loginCount: CodecTypes['pg/int4@1']['input'];
      readonly supportToastDismissed: CodecTypes['pg/bool@1']['input'];
      readonly supportToastPending: CodecTypes['pg/bool@1']['input'];
      readonly lastSeenAt: CodecTypes['pg/timestamp-string@1']['input'] | null;
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly _prisma_migrations: {
      readonly applied_steps_count: CodecTypes['pg/int4@1']['output'];
      readonly checksum: Varchar<64>;
      readonly finished_at: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly id: Varchar<36>;
      readonly logs: CodecTypes['pg/text@1']['output'] | null;
      readonly migration_name: Varchar<255>;
      readonly rolled_back_at: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly started_at: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly crate_releases: {
      readonly added_at: TimestampString<3>;
      readonly crate_id: CodecTypes['pg/text@1']['output'];
      readonly found_at: TimestampString<3> | null;
      readonly instance_id: CodecTypes['pg/text@1']['output'];
      readonly release_data: CodecTypes['pg/jsonb@1']['output'];
      readonly sort_order: CodecTypes['pg/int4@1']['output'];
      readonly user_id: CodecTypes['pg/int4@1']['output'];
    };
    readonly crate_set_markers: {
      readonly crate_id: CodecTypes['pg/text@1']['output'];
      readonly created_at: TimestampString<3>;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly label: CodecTypes['pg/text@1']['output'];
      readonly sort_order: CodecTypes['pg/int4@1']['output'];
      readonly updated_at: TimestampString<3>;
      readonly user_id: CodecTypes['pg/int4@1']['output'];
    };
    readonly crates: {
      readonly created_at: TimestampString<3>;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly is_default: CodecTypes['pg/bool@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly notes: CodecTypes['pg/text@1']['output'] | null;
      readonly packed_enabled: CodecTypes['pg/bool@1']['output'];
      readonly private: CodecTypes['pg/bool@1']['output'];
      readonly updated_at: TimestampString<3>;
      readonly user_id: CodecTypes['pg/int4@1']['output'];
      readonly username: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly product_analytics_daily_rollups: {
      readonly date: CodecTypes['pg/date-string@1']['output'];
      readonly dimension_key: CodecTypes['pg/text@1']['output'];
      readonly dimension_type: CodecTypes['pg/text@1']['output'];
      readonly event_count: CodecTypes['pg/int4@1']['output'];
    };
    readonly product_analytics_events: {
      readonly action: CodecTypes['pg/text@1']['output'];
      readonly category: CodecTypes['pg/text@1']['output'];
      readonly created_at: TimestampString<3>;
      readonly event: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly label: CodecTypes['pg/text@1']['output'];
      readonly page_path: CodecTypes['pg/text@1']['output'] | null;
      readonly user_id: CodecTypes['pg/int4@1']['output'] | null;
      readonly value: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly users: {
      readonly created_at: TimestampString<3>;
      readonly discogs_user_id: CodecTypes['pg/int4@1']['output'];
      readonly last_seen_at: TimestampString<3> | null;
      readonly login_count: CodecTypes['pg/int4@1']['output'];
      readonly preferences: CodecTypes['pg/jsonb@1']['output'];
      readonly support_toast_dismissed: CodecTypes['pg/bool@1']['output'];
      readonly support_toast_pending: CodecTypes['pg/bool@1']['output'];
      readonly updated_at: TimestampString<3>;
      readonly username: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly _prisma_migrations: {
      readonly applied_steps_count: CodecTypes['pg/int4@1']['input'];
      readonly checksum: CodecTypes['sql/varchar@1']['input'];
      readonly finished_at: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly id: CodecTypes['sql/varchar@1']['input'];
      readonly logs: CodecTypes['pg/text@1']['input'] | null;
      readonly migration_name: CodecTypes['sql/varchar@1']['input'];
      readonly rolled_back_at: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly started_at: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly crate_releases: {
      readonly added_at: CodecTypes['pg/timestamp-string@1']['input'];
      readonly crate_id: CodecTypes['pg/text@1']['input'];
      readonly found_at: CodecTypes['pg/timestamp-string@1']['input'] | null;
      readonly instance_id: CodecTypes['pg/text@1']['input'];
      readonly release_data: CodecTypes['pg/jsonb@1']['input'];
      readonly sort_order: CodecTypes['pg/int4@1']['input'];
      readonly user_id: CodecTypes['pg/int4@1']['input'];
    };
    readonly crate_set_markers: {
      readonly crate_id: CodecTypes['pg/text@1']['input'];
      readonly created_at: CodecTypes['pg/timestamp-string@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly label: CodecTypes['pg/text@1']['input'];
      readonly sort_order: CodecTypes['pg/int4@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamp-string@1']['input'];
      readonly user_id: CodecTypes['pg/int4@1']['input'];
    };
    readonly crates: {
      readonly created_at: CodecTypes['pg/timestamp-string@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly is_default: CodecTypes['pg/bool@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly notes: CodecTypes['pg/text@1']['input'] | null;
      readonly packed_enabled: CodecTypes['pg/bool@1']['input'];
      readonly private: CodecTypes['pg/bool@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamp-string@1']['input'];
      readonly user_id: CodecTypes['pg/int4@1']['input'];
      readonly username: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly product_analytics_daily_rollups: {
      readonly date: CodecTypes['pg/date-string@1']['input'];
      readonly dimension_key: CodecTypes['pg/text@1']['input'];
      readonly dimension_type: CodecTypes['pg/text@1']['input'];
      readonly event_count: CodecTypes['pg/int4@1']['input'];
    };
    readonly product_analytics_events: {
      readonly action: CodecTypes['pg/text@1']['input'];
      readonly category: CodecTypes['pg/text@1']['input'];
      readonly created_at: CodecTypes['pg/timestamp-string@1']['input'];
      readonly event: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly label: CodecTypes['pg/text@1']['input'];
      readonly page_path: CodecTypes['pg/text@1']['input'] | null;
      readonly user_id: CodecTypes['pg/int4@1']['input'] | null;
      readonly value: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly users: {
      readonly created_at: CodecTypes['pg/timestamp-string@1']['input'];
      readonly discogs_user_id: CodecTypes['pg/int4@1']['input'];
      readonly last_seen_at: CodecTypes['pg/timestamp-string@1']['input'] | null;
      readonly login_count: CodecTypes['pg/int4@1']['input'];
      readonly preferences: CodecTypes['pg/jsonb@1']['input'];
      readonly support_toast_dismissed: CodecTypes['pg/bool@1']['input'];
      readonly support_toast_pending: CodecTypes['pg/bool@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamp-string@1']['input'];
      readonly username: CodecTypes['pg/text@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly _prisma_migrations: {
              columns: {
                readonly id: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly checksum: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 64 };
                };
                readonly finished_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
                readonly migration_name: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 255 };
                };
                readonly logs: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly rolled_back_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
                readonly started_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly applied_steps_count: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
              };
              primaryKey: {
                readonly columns: readonly ['id'];
                readonly name: '_prisma_migrations_pkey';
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly crate_releases: {
              columns: {
                readonly user_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly crate_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly instance_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly release_data: {
                  readonly nativeType: 'jsonb';
                  readonly codecId: 'pg/jsonb@1';
                  readonly nullable: false;
                };
                readonly added_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly found_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly sort_order: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
              };
              primaryKey: {
                readonly columns: readonly ['user_id', 'crate_id', 'instance_id'];
                readonly name: 'crate_releases_pkey';
              };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'crate_releases_added_at_idx';
                  readonly columns: readonly ['added_at'];
                  readonly unique: false;
                },
                {
                  readonly name: 'crate_releases_user_id_crate_id_added_at_idx';
                  readonly columns: readonly ['user_id', 'crate_id', 'added_at'];
                  readonly unique: false;
                },
                {
                  readonly name: 'crate_releases_user_id_crate_id_idx';
                  readonly columns: readonly ['user_id', 'crate_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'crate_releases_user_id_crate_id_sort_order_idx';
                  readonly columns: readonly ['user_id', 'crate_id', 'sort_order'];
                  readonly unique: false;
                },
                {
                  readonly name: 'crate_releases_user_id_instance_id_idx';
                  readonly columns: readonly ['user_id', 'instance_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'crate_releases';
                    readonly columns: readonly ['user_id', 'crate_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'crates';
                    readonly columns: readonly ['user_id', 'id'];
                  };
                  readonly name: 'crate_releases_user_id_crate_id_fkey';
                },
              ];
            };
            readonly crate_set_markers: {
              columns: {
                readonly user_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly crate_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly label: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly sort_order: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              primaryKey: {
                readonly columns: readonly ['user_id', 'crate_id', 'id'];
                readonly name: 'crate_set_markers_pkey';
              };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'crate_set_markers_user_id_crate_id_sort_order_idx';
                  readonly columns: readonly ['user_id', 'crate_id', 'sort_order'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'crate_set_markers';
                    readonly columns: readonly ['user_id', 'crate_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'crates';
                    readonly columns: readonly ['user_id', 'id'];
                  };
                  readonly name: 'crate_set_markers_user_id_crate_id_fkey';
                },
              ];
            };
            readonly crates: {
              columns: {
                readonly user_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly is_default: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly created_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly private: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly username: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly packed_enabled: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly notes: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: {
                readonly columns: readonly ['user_id', 'id'];
                readonly name: 'crates_pkey';
              };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'crates_id_private_idx';
                  readonly columns: readonly ['id', 'private'];
                  readonly unique: false;
                },
                {
                  readonly name: 'crates_user_id_idx';
                  readonly columns: readonly ['user_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'crates_user_id_is_default_idx';
                  readonly columns: readonly ['user_id', 'is_default'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'crates';
                    readonly columns: readonly ['user_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'users';
                    readonly columns: readonly ['discogs_user_id'];
                  };
                  readonly name: 'crates_user_id_fkey';
                },
              ];
            };
            readonly product_analytics_daily_rollups: {
              columns: {
                readonly date: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-string@1';
                  readonly nullable: false;
                };
                readonly dimension_type: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly dimension_key: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly event_count: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: {
                readonly columns: readonly ['date', 'dimension_type', 'dimension_key'];
                readonly name: 'product_analytics_daily_rollups_pkey';
              };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'product_analytics_daily_rollups_date_idx';
                  readonly columns: readonly ['date'];
                  readonly unique: false;
                },
                {
                  readonly name: 'product_analytics_daily_rollups_dimension_type_date_idx';
                  readonly columns: readonly ['dimension_type', 'date'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly product_analytics_events: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly event: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly category: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly action: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly label: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly value: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly page_path: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly user_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              primaryKey: {
                readonly columns: readonly ['id'];
                readonly name: 'product_analytics_events_pkey';
              };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'product_analytics_events_created_at_idx';
                  readonly columns: readonly ['created_at'];
                  readonly unique: false;
                },
                {
                  readonly name: 'product_analytics_events_event_created_at_idx';
                  readonly columns: readonly ['event', 'created_at'];
                  readonly unique: false;
                },
                {
                  readonly name: 'product_analytics_events_page_path_created_at_idx';
                  readonly columns: readonly ['page_path', 'created_at'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly users: {
              columns: {
                readonly discogs_user_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly username: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly preferences: {
                  readonly nativeType: 'jsonb';
                  readonly codecId: 'pg/jsonb@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: "'{}'::jsonb";
                  };
                };
                readonly login_count: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly support_toast_dismissed: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly support_toast_pending: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly last_seen_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              primaryKey: {
                readonly columns: readonly ['discogs_user_id'];
                readonly name: 'users_pkey';
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly users: { readonly namespace: 'public' & NamespaceId; readonly model: 'Users' };
    readonly crates: { readonly namespace: 'public' & NamespaceId; readonly model: 'Crates' };
    readonly crate_releases: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'CrateReleases';
    };
    readonly crate_set_markers: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'CrateSetMarkers';
    };
    readonly _prisma_migrations: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'PrismaMigrations';
    };
    readonly product_analytics_daily_rollups: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ProductAnalyticsDailyRollups';
    };
    readonly product_analytics_events: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ProductAnalyticsEvents';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly CrateReleases: {
            readonly fields: {
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly crateId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly instanceId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly releaseData: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/jsonb@1' };
              };
              readonly addedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly foundAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly sortOrder: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly crates: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Crates';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['userId', 'crateId'];
                  readonly targetFields: readonly ['userId', 'id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'crate_releases';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly userId: { readonly column: 'user_id' };
                readonly crateId: { readonly column: 'crate_id' };
                readonly instanceId: { readonly column: 'instance_id' };
                readonly releaseData: { readonly column: 'release_data' };
                readonly addedAt: { readonly column: 'added_at' };
                readonly foundAt: { readonly column: 'found_at' };
                readonly sortOrder: { readonly column: 'sort_order' };
              };
            };
          };
          readonly Crates: {
            readonly fields: {
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly isDefault: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly private: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly username: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly packedEnabled: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly notes: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly crateReleases: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'CrateReleases';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['userId', 'id'];
                  readonly targetFields: readonly ['userId', 'crateId'];
                };
              };
              readonly crateSetMarkers: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'CrateSetMarkers';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['userId', 'id'];
                  readonly targetFields: readonly ['userId', 'crateId'];
                };
              };
              readonly user: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Users';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['discogsUserId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'crates';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly userId: { readonly column: 'user_id' };
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly isDefault: { readonly column: 'is_default' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly updatedAt: { readonly column: 'updated_at' };
                readonly private: { readonly column: 'private' };
                readonly username: { readonly column: 'username' };
                readonly packedEnabled: { readonly column: 'packed_enabled' };
                readonly notes: { readonly column: 'notes' };
              };
            };
          };
          readonly CrateSetMarkers: {
            readonly fields: {
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly crateId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly label: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly sortOrder: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
            };
            readonly relations: {
              readonly crates: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Crates';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['userId', 'crateId'];
                  readonly targetFields: readonly ['userId', 'id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'crate_set_markers';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly userId: { readonly column: 'user_id' };
                readonly crateId: { readonly column: 'crate_id' };
                readonly id: { readonly column: 'id' };
                readonly label: { readonly column: 'label' };
                readonly sortOrder: { readonly column: 'sort_order' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly updatedAt: { readonly column: 'updated_at' };
              };
            };
          };
          readonly PrismaMigrations: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly checksum: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 64 };
                };
              };
              readonly finishedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly migrationName: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
              readonly logs: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly rolledBackAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly startedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly appliedStepsCount: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: '_prisma_migrations';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly checksum: { readonly column: 'checksum' };
                readonly finishedAt: { readonly column: 'finished_at' };
                readonly migrationName: { readonly column: 'migration_name' };
                readonly logs: { readonly column: 'logs' };
                readonly rolledBackAt: { readonly column: 'rolled_back_at' };
                readonly startedAt: { readonly column: 'started_at' };
                readonly appliedStepsCount: { readonly column: 'applied_steps_count' };
              };
            };
          };
          readonly ProductAnalyticsDailyRollups: {
            readonly fields: {
              readonly date: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-string@1' };
              };
              readonly dimensionType: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly dimensionKey: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly eventCount: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'product_analytics_daily_rollups';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly date: { readonly column: 'date' };
                readonly dimensionType: { readonly column: 'dimension_type' };
                readonly dimensionKey: { readonly column: 'dimension_key' };
                readonly eventCount: { readonly column: 'event_count' };
              };
            };
          };
          readonly ProductAnalyticsEvents: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly event: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly category: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly action: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly label: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly value: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly pagePath: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly userId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'product_analytics_events';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly event: { readonly column: 'event' };
                readonly category: { readonly column: 'category' };
                readonly action: { readonly column: 'action' };
                readonly label: { readonly column: 'label' };
                readonly value: { readonly column: 'value' };
                readonly pagePath: { readonly column: 'page_path' };
                readonly userId: { readonly column: 'user_id' };
                readonly createdAt: { readonly column: 'created_at' };
              };
            };
          };
          readonly Users: {
            readonly fields: {
              readonly discogsUserId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly username: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly preferences: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/jsonb@1' };
              };
              readonly loginCount: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly supportToastDismissed: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly supportToastPending: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly lastSeenAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
            };
            readonly relations: {
              readonly crates: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Crates';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['discogsUserId'];
                  readonly targetFields: readonly ['userId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'users';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly discogsUserId: { readonly column: 'discogs_user_id' };
                readonly username: { readonly column: 'username' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly updatedAt: { readonly column: 'updated_at' };
                readonly preferences: { readonly column: 'preferences' };
                readonly loginCount: { readonly column: 'login_count' };
                readonly supportToastDismissed: { readonly column: 'support_toast_dismissed' };
                readonly supportToastPending: { readonly column: 'support_toast_pending' };
                readonly lastSeenAt: { readonly column: 'last_seen_at' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
