// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type {
  CodecTypes as PgTypes,
  TimestampString,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';
import type { QueryOperationTypes as PgTargetQueryOps } from '@prisma/orm-postgres/target/operation-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'8ff8e97c7313fae28bb8683bded1d5c7ff328e94ff820babb1f63df10c0f8e87'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgTargetQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly CrateReleases: {
      readonly addedAt: TimestampString<3>;
      readonly crateId: CodecTypes['pg/text@1']['output'];
      readonly foundAt: TimestampString<3> | null;
      readonly instanceId: CodecTypes['pg/text@1']['output'];
      readonly releaseData: CodecTypes['pg/jsonb@1']['output'];
      readonly sectionId: CodecTypes['pg/text@1']['output'] | null;
      readonly sortOrder: CodecTypes['pg/int4@1']['output'];
      readonly userId: CodecTypes['pg/int4@1']['output'];
    };
    readonly Crates: {
      readonly createdAt: TimestampString<3>;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly isDefault: CodecTypes['pg/bool@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly notes: CodecTypes['pg/text@1']['output'] | null;
      readonly packedEnabled: CodecTypes['pg/bool@1']['output'];
      readonly private: CodecTypes['pg/bool@1']['output'];
      readonly updatedAt: TimestampString<3>;
      readonly userId: CodecTypes['pg/int4@1']['output'];
      readonly username: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly CrateSetMarkers: {
      readonly accentKey: CodecTypes['pg/text@1']['output'] | null;
      readonly crateId: CodecTypes['pg/text@1']['output'];
      readonly createdAt: TimestampString<3>;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly label: CodecTypes['pg/text@1']['output'];
      readonly parentId: CodecTypes['pg/text@1']['output'] | null;
      readonly sortOrder: CodecTypes['pg/int4@1']['output'];
      readonly updatedAt: TimestampString<3>;
      readonly userId: CodecTypes['pg/int4@1']['output'];
    };
    readonly PrismaMigrations: {
      readonly appliedStepsCount: CodecTypes['pg/int4@1']['output'];
      readonly checksum: Varchar<64>;
      readonly finishedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly id: Varchar<36>;
      readonly logs: CodecTypes['pg/text@1']['output'] | null;
      readonly migrationName: Varchar<255>;
      readonly rolledBackAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly startedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly ProductAnalyticsDailyRollups: {
      readonly date: CodecTypes['pg/date-string@1']['output'];
      readonly dimensionKey: CodecTypes['pg/text@1']['output'];
      readonly dimensionType: CodecTypes['pg/text@1']['output'];
      readonly eventCount: CodecTypes['pg/int4@1']['output'];
    };
    readonly ProductAnalyticsEvents: {
      readonly action: CodecTypes['pg/text@1']['output'];
      readonly category: CodecTypes['pg/text@1']['output'];
      readonly createdAt: TimestampString<3>;
      readonly event: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly label: CodecTypes['pg/text@1']['output'];
      readonly pagePath: CodecTypes['pg/text@1']['output'] | null;
      readonly userId: CodecTypes['pg/int4@1']['output'] | null;
      readonly value: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly Users: {
      readonly createdAt: TimestampString<3>;
      readonly discogsUserId: CodecTypes['pg/int4@1']['output'];
      readonly lastSeenAt: TimestampString<3> | null;
      readonly loginCount: CodecTypes['pg/int4@1']['output'];
      readonly preferences: CodecTypes['pg/jsonb@1']['output'];
      readonly supportToastDismissed: CodecTypes['pg/bool@1']['output'];
      readonly supportToastPending: CodecTypes['pg/bool@1']['output'];
      readonly updatedAt: TimestampString<3>;
      readonly username: CodecTypes['pg/text@1']['output'];
    };
    readonly UserTracks: {
      readonly artist: CodecTypes['pg/text@1']['output'] | null;
      readonly firstPlayedAt: TimestampString<3>;
      readonly instanceId: CodecTypes['pg/text@1']['output'];
      readonly lastListenedAt: TimestampString<3> | null;
      readonly lastPlayedAt: TimestampString<3> | null;
      readonly listenCount: CodecTypes['pg/int4@1']['output'];
      readonly playCount: CodecTypes['pg/int4@1']['output'];
      readonly releaseTitle: CodecTypes['pg/text@1']['output'] | null;
      readonly trackKey: CodecTypes['pg/text@1']['output'];
      readonly trackPosition: CodecTypes['pg/text@1']['output'];
      readonly trackTitle: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: TimestampString<3>;
      readonly userId: CodecTypes['pg/int4@1']['output'];
      readonly youtubeId: CodecTypes['pg/text@1']['output'] | null;
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly CrateReleases: {
      readonly addedAt: CodecTypes['pg/timestamp-string@1']['input'];
      readonly crateId: CodecTypes['pg/text@1']['input'];
      readonly foundAt: CodecTypes['pg/timestamp-string@1']['input'] | null;
      readonly instanceId: CodecTypes['pg/text@1']['input'];
      readonly releaseData: CodecTypes['pg/jsonb@1']['input'];
      readonly sectionId: CodecTypes['pg/text@1']['input'] | null;
      readonly sortOrder: CodecTypes['pg/int4@1']['input'];
      readonly userId: CodecTypes['pg/int4@1']['input'];
    };
    readonly Crates: {
      readonly createdAt: CodecTypes['pg/timestamp-string@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly isDefault: CodecTypes['pg/bool@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly notes: CodecTypes['pg/text@1']['input'] | null;
      readonly packedEnabled: CodecTypes['pg/bool@1']['input'];
      readonly private: CodecTypes['pg/bool@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamp-string@1']['input'];
      readonly userId: CodecTypes['pg/int4@1']['input'];
      readonly username: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly CrateSetMarkers: {
      readonly accentKey: CodecTypes['pg/text@1']['input'] | null;
      readonly crateId: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamp-string@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly label: CodecTypes['pg/text@1']['input'];
      readonly parentId: CodecTypes['pg/text@1']['input'] | null;
      readonly sortOrder: CodecTypes['pg/int4@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamp-string@1']['input'];
      readonly userId: CodecTypes['pg/int4@1']['input'];
    };
    readonly PrismaMigrations: {
      readonly appliedStepsCount: CodecTypes['pg/int4@1']['input'];
      readonly checksum: CodecTypes['sql/varchar@1']['input'];
      readonly finishedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly id: CodecTypes['sql/varchar@1']['input'];
      readonly logs: CodecTypes['pg/text@1']['input'] | null;
      readonly migrationName: CodecTypes['sql/varchar@1']['input'];
      readonly rolledBackAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly startedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly ProductAnalyticsDailyRollups: {
      readonly date: CodecTypes['pg/date-string@1']['input'];
      readonly dimensionKey: CodecTypes['pg/text@1']['input'];
      readonly dimensionType: CodecTypes['pg/text@1']['input'];
      readonly eventCount: CodecTypes['pg/int4@1']['input'];
    };
    readonly ProductAnalyticsEvents: {
      readonly action: CodecTypes['pg/text@1']['input'];
      readonly category: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamp-string@1']['input'];
      readonly event: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly label: CodecTypes['pg/text@1']['input'];
      readonly pagePath: CodecTypes['pg/text@1']['input'] | null;
      readonly userId: CodecTypes['pg/int4@1']['input'] | null;
      readonly value: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly Users: {
      readonly createdAt: CodecTypes['pg/timestamp-string@1']['input'];
      readonly discogsUserId: CodecTypes['pg/int4@1']['input'];
      readonly lastSeenAt: CodecTypes['pg/timestamp-string@1']['input'] | null;
      readonly loginCount: CodecTypes['pg/int4@1']['input'];
      readonly preferences: CodecTypes['pg/jsonb@1']['input'];
      readonly supportToastDismissed: CodecTypes['pg/bool@1']['input'];
      readonly supportToastPending: CodecTypes['pg/bool@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamp-string@1']['input'];
      readonly username: CodecTypes['pg/text@1']['input'];
    };
    readonly UserTracks: {
      readonly artist: CodecTypes['pg/text@1']['input'] | null;
      readonly firstPlayedAt: CodecTypes['pg/timestamp-string@1']['input'];
      readonly instanceId: CodecTypes['pg/text@1']['input'];
      readonly lastListenedAt: CodecTypes['pg/timestamp-string@1']['input'] | null;
      readonly lastPlayedAt: CodecTypes['pg/timestamp-string@1']['input'] | null;
      readonly listenCount: CodecTypes['pg/int4@1']['input'];
      readonly playCount: CodecTypes['pg/int4@1']['input'];
      readonly releaseTitle: CodecTypes['pg/text@1']['input'] | null;
      readonly trackKey: CodecTypes['pg/text@1']['input'];
      readonly trackPosition: CodecTypes['pg/text@1']['input'];
      readonly trackTitle: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamp-string@1']['input'];
      readonly userId: CodecTypes['pg/int4@1']['input'];
      readonly youtubeId: CodecTypes['pg/text@1']['input'] | null;
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly _prisma_migrations: {
      readonly applied_steps_count: CodecTypes['pg/int4@1']['output'];
      readonly checksum: Varchar<64>;
      readonly finished_at: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly id: Varchar<36>;
      readonly logs: CodecTypes['pg/text@1']['output'] | null;
      readonly migration_name: Varchar<255>;
      readonly rolled_back_at: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly started_at: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly crate_releases: {
      readonly added_at: TimestampString<3>;
      readonly crate_id: CodecTypes['pg/text@1']['output'];
      readonly found_at: TimestampString<3> | null;
      readonly instance_id: CodecTypes['pg/text@1']['output'];
      readonly release_data: CodecTypes['pg/jsonb@1']['output'];
      readonly section_id: CodecTypes['pg/text@1']['output'] | null;
      readonly sort_order: CodecTypes['pg/int4@1']['output'];
      readonly user_id: CodecTypes['pg/int4@1']['output'];
    };
    readonly crate_set_markers: {
      readonly accent_key: CodecTypes['pg/text@1']['output'] | null;
      readonly crate_id: CodecTypes['pg/text@1']['output'];
      readonly created_at: TimestampString<3>;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly label: CodecTypes['pg/text@1']['output'];
      readonly parent_id: CodecTypes['pg/text@1']['output'] | null;
      readonly sort_order: CodecTypes['pg/int4@1']['output'];
      readonly updated_at: TimestampString<3>;
      readonly user_id: CodecTypes['pg/int4@1']['output'];
    };
    readonly crates: {
      readonly created_at: TimestampString<3>;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly is_default: CodecTypes['pg/bool@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly notes: CodecTypes['pg/text@1']['output'] | null;
      readonly packed_enabled: CodecTypes['pg/bool@1']['output'];
      readonly private: CodecTypes['pg/bool@1']['output'];
      readonly updated_at: TimestampString<3>;
      readonly user_id: CodecTypes['pg/int4@1']['output'];
      readonly username: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly product_analytics_daily_rollups: {
      readonly date: CodecTypes['pg/date-string@1']['output'];
      readonly dimension_key: CodecTypes['pg/text@1']['output'];
      readonly dimension_type: CodecTypes['pg/text@1']['output'];
      readonly event_count: CodecTypes['pg/int4@1']['output'];
    };
    readonly product_analytics_events: {
      readonly action: CodecTypes['pg/text@1']['output'];
      readonly category: CodecTypes['pg/text@1']['output'];
      readonly created_at: TimestampString<3>;
      readonly event: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly label: CodecTypes['pg/text@1']['output'];
      readonly page_path: CodecTypes['pg/text@1']['output'] | null;
      readonly user_id: CodecTypes['pg/int4@1']['output'] | null;
      readonly value: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly user_tracks: {
      readonly artist: CodecTypes['pg/text@1']['output'] | null;
      readonly first_played_at: TimestampString<3>;
      readonly instance_id: CodecTypes['pg/text@1']['output'];
      readonly last_listened_at: TimestampString<3> | null;
      readonly last_played_at: TimestampString<3> | null;
      readonly listen_count: CodecTypes['pg/int4@1']['output'];
      readonly play_count: CodecTypes['pg/int4@1']['output'];
      readonly release_title: CodecTypes['pg/text@1']['output'] | null;
      readonly track_key: CodecTypes['pg/text@1']['output'];
      readonly track_position: CodecTypes['pg/text@1']['output'];
      readonly track_title: CodecTypes['pg/text@1']['output'];
      readonly updated_at: TimestampString<3>;
      readonly user_id: CodecTypes['pg/int4@1']['output'];
      readonly youtube_id: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly users: {
      readonly created_at: TimestampString<3>;
      readonly discogs_user_id: CodecTypes['pg/int4@1']['output'];
      readonly last_seen_at: TimestampString<3> | null;
      readonly login_count: CodecTypes['pg/int4@1']['output'];
      readonly preferences: CodecTypes['pg/jsonb@1']['output'];
      readonly support_toast_dismissed: CodecTypes['pg/bool@1']['output'];
      readonly support_toast_pending: CodecTypes['pg/bool@1']['output'];
      readonly updated_at: TimestampString<3>;
      readonly username: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly _prisma_migrations: {
      readonly applied_steps_count: CodecTypes['pg/int4@1']['input'];
      readonly checksum: CodecTypes['sql/varchar@1']['input'];
      readonly finished_at: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly id: CodecTypes['sql/varchar@1']['input'];
      readonly logs: CodecTypes['pg/text@1']['input'] | null;
      readonly migration_name: CodecTypes['sql/varchar@1']['input'];
      readonly rolled_back_at: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly started_at: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly crate_releases: {
      readonly added_at: CodecTypes['pg/timestamp-string@1']['input'];
      readonly crate_id: CodecTypes['pg/text@1']['input'];
      readonly found_at: CodecTypes['pg/timestamp-string@1']['input'] | null;
      readonly instance_id: CodecTypes['pg/text@1']['input'];
      readonly release_data: CodecTypes['pg/jsonb@1']['input'];
      readonly section_id: CodecTypes['pg/text@1']['input'] | null;
      readonly sort_order: CodecTypes['pg/int4@1']['input'];
      readonly user_id: CodecTypes['pg/int4@1']['input'];
    };
    readonly crate_set_markers: {
      readonly accent_key: CodecTypes['pg/text@1']['input'] | null;
      readonly crate_id: CodecTypes['pg/text@1']['input'];
      readonly created_at: CodecTypes['pg/timestamp-string@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly label: CodecTypes['pg/text@1']['input'];
      readonly parent_id: CodecTypes['pg/text@1']['input'] | null;
      readonly sort_order: CodecTypes['pg/int4@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamp-string@1']['input'];
      readonly user_id: CodecTypes['pg/int4@1']['input'];
    };
    readonly crates: {
      readonly created_at: CodecTypes['pg/timestamp-string@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly is_default: CodecTypes['pg/bool@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly notes: CodecTypes['pg/text@1']['input'] | null;
      readonly packed_enabled: CodecTypes['pg/bool@1']['input'];
      readonly private: CodecTypes['pg/bool@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamp-string@1']['input'];
      readonly user_id: CodecTypes['pg/int4@1']['input'];
      readonly username: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly product_analytics_daily_rollups: {
      readonly date: CodecTypes['pg/date-string@1']['input'];
      readonly dimension_key: CodecTypes['pg/text@1']['input'];
      readonly dimension_type: CodecTypes['pg/text@1']['input'];
      readonly event_count: CodecTypes['pg/int4@1']['input'];
    };
    readonly product_analytics_events: {
      readonly action: CodecTypes['pg/text@1']['input'];
      readonly category: CodecTypes['pg/text@1']['input'];
      readonly created_at: CodecTypes['pg/timestamp-string@1']['input'];
      readonly event: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly label: CodecTypes['pg/text@1']['input'];
      readonly page_path: CodecTypes['pg/text@1']['input'] | null;
      readonly user_id: CodecTypes['pg/int4@1']['input'] | null;
      readonly value: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly user_tracks: {
      readonly artist: CodecTypes['pg/text@1']['input'] | null;
      readonly first_played_at: CodecTypes['pg/timestamp-string@1']['input'];
      readonly instance_id: CodecTypes['pg/text@1']['input'];
      readonly last_listened_at: CodecTypes['pg/timestamp-string@1']['input'] | null;
      readonly last_played_at: CodecTypes['pg/timestamp-string@1']['input'] | null;
      readonly listen_count: CodecTypes['pg/int4@1']['input'];
      readonly play_count: CodecTypes['pg/int4@1']['input'];
      readonly release_title: CodecTypes['pg/text@1']['input'] | null;
      readonly track_key: CodecTypes['pg/text@1']['input'];
      readonly track_position: CodecTypes['pg/text@1']['input'];
      readonly track_title: CodecTypes['pg/text@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamp-string@1']['input'];
      readonly user_id: CodecTypes['pg/int4@1']['input'];
      readonly youtube_id: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly users: {
      readonly created_at: CodecTypes['pg/timestamp-string@1']['input'];
      readonly discogs_user_id: CodecTypes['pg/int4@1']['input'];
      readonly last_seen_at: CodecTypes['pg/timestamp-string@1']['input'] | null;
      readonly login_count: CodecTypes['pg/int4@1']['input'];
      readonly preferences: CodecTypes['pg/jsonb@1']['input'];
      readonly support_toast_dismissed: CodecTypes['pg/bool@1']['input'];
      readonly support_toast_pending: CodecTypes['pg/bool@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamp-string@1']['input'];
      readonly username: CodecTypes['pg/text@1']['input'];
    };
  };
};

export namespace Models {
  export type public_CrateReleases = {
    addedAt: TimestampString<3>;
    crateId: CodecTypes['pg/text@1']['output'];
    foundAt: TimestampString<3> | null;
    instanceId: CodecTypes['pg/text@1']['output'];
    releaseData: CodecTypes['pg/jsonb@1']['output'];
    sectionId: CodecTypes['pg/text@1']['output'] | null;
    sortOrder: CodecTypes['pg/int4@1']['output'];
    userId: CodecTypes['pg/int4@1']['output'];
    crates: public_Crates;
    readonly [RelationKeys]?: 'crates';
  };
  export type public_CrateSetMarkers = {
    accentKey: CodecTypes['pg/text@1']['output'] | null;
    crateId: CodecTypes['pg/text@1']['output'];
    createdAt: TimestampString<3>;
    id: CodecTypes['pg/text@1']['output'];
    label: CodecTypes['pg/text@1']['output'];
    parentId: CodecTypes['pg/text@1']['output'] | null;
    sortOrder: CodecTypes['pg/int4@1']['output'];
    updatedAt: TimestampString<3>;
    userId: CodecTypes['pg/int4@1']['output'];
    crates: public_Crates;
    readonly [RelationKeys]?: 'crates';
  };
  export type public_Crates = {
    createdAt: TimestampString<3>;
    id: CodecTypes['pg/text@1']['output'];
    isDefault: CodecTypes['pg/bool@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    notes: CodecTypes['pg/text@1']['output'] | null;
    packedEnabled: CodecTypes['pg/bool@1']['output'];
    private: CodecTypes['pg/bool@1']['output'];
    updatedAt: TimestampString<3>;
    userId: CodecTypes['pg/int4@1']['output'];
    username: CodecTypes['pg/text@1']['output'] | null;
    crateReleases: public_CrateReleases[];
    crateSetMarkers: public_CrateSetMarkers[];
    user: public_Users;
    readonly [RelationKeys]?: 'crateReleases' | 'crateSetMarkers' | 'user';
  };
  export type public_PrismaMigrations = {
    appliedStepsCount: CodecTypes['pg/int4@1']['output'];
    checksum: Varchar<64>;
    finishedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
    id: Varchar<36>;
    logs: CodecTypes['pg/text@1']['output'] | null;
    migrationName: Varchar<255>;
    rolledBackAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
    startedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type public_ProductAnalyticsDailyRollups = {
    date: CodecTypes['pg/date-string@1']['output'];
    dimensionKey: CodecTypes['pg/text@1']['output'];
    dimensionType: CodecTypes['pg/text@1']['output'];
    eventCount: CodecTypes['pg/int4@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type public_ProductAnalyticsEvents = {
    action: CodecTypes['pg/text@1']['output'];
    category: CodecTypes['pg/text@1']['output'];
    createdAt: TimestampString<3>;
    event: CodecTypes['pg/text@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    label: CodecTypes['pg/text@1']['output'];
    pagePath: CodecTypes['pg/text@1']['output'] | null;
    userId: CodecTypes['pg/int4@1']['output'] | null;
    value: CodecTypes['pg/text@1']['output'] | null;
    readonly [RelationKeys]?: never;
  };
  export type public_UserTracks = {
    artist: CodecTypes['pg/text@1']['output'] | null;
    firstPlayedAt: TimestampString<3>;
    instanceId: CodecTypes['pg/text@1']['output'];
    lastListenedAt: TimestampString<3> | null;
    lastPlayedAt: TimestampString<3> | null;
    listenCount: CodecTypes['pg/int4@1']['output'];
    playCount: CodecTypes['pg/int4@1']['output'];
    releaseTitle: CodecTypes['pg/text@1']['output'] | null;
    trackKey: CodecTypes['pg/text@1']['output'];
    trackPosition: CodecTypes['pg/text@1']['output'];
    trackTitle: CodecTypes['pg/text@1']['output'];
    updatedAt: TimestampString<3>;
    userId: CodecTypes['pg/int4@1']['output'];
    youtubeId: CodecTypes['pg/text@1']['output'] | null;
    user: public_Users;
    readonly [RelationKeys]?: 'user';
  };
  export type public_Users = {
    createdAt: TimestampString<3>;
    discogsUserId: CodecTypes['pg/int4@1']['output'];
    lastSeenAt: TimestampString<3> | null;
    loginCount: CodecTypes['pg/int4@1']['output'];
    preferences: CodecTypes['pg/jsonb@1']['output'];
    supportToastDismissed: CodecTypes['pg/bool@1']['output'];
    supportToastPending: CodecTypes['pg/bool@1']['output'];
    updatedAt: TimestampString<3>;
    username: CodecTypes['pg/text@1']['output'];
    crates: public_Crates[];
    userTracks: public_UserTracks[];
    readonly [RelationKeys]?: 'crates' | 'userTracks';
  };
}

export declare const models: {
  public: {
    CrateReleases: Models.public_CrateReleases;
    CrateSetMarkers: Models.public_CrateSetMarkers;
    Crates: Models.public_Crates;
    PrismaMigrations: Models.public_PrismaMigrations;
    ProductAnalyticsDailyRollups: Models.public_ProductAnalyticsDailyRollups;
    ProductAnalyticsEvents: Models.public_ProductAnalyticsEvents;
    UserTracks: Models.public_UserTracks;
    Users: Models.public_Users;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly _prisma_migrations: {
              columns: {
                readonly applied_steps_count: {
                  readonly dataType: 'pg/int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                  readonly many: false;
                };
                readonly checksum: {
                  readonly dataType: 'pg/varchar';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 64 };
                  readonly many: false;
                };
                readonly finished_at: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly id: {
                  readonly dataType: 'pg/varchar';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                  readonly many: false;
                };
                readonly logs: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly migration_name: {
                  readonly dataType: 'pg/varchar';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 255 };
                  readonly many: false;
                };
                readonly rolled_back_at: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly started_at: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly many: false;
                };
              };
              primaryKey: {
                readonly columns: readonly ['id'];
                readonly name: '_prisma_migrations_pkey';
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly crate_releases: {
              columns: {
                readonly added_at: {
                  readonly dataType: 'pg/timestamp';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                  readonly many: false;
                };
                readonly crate_id: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly found_at: {
                  readonly dataType: 'pg/timestamp';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly precision: 3 };
                  readonly many: false;
                };
                readonly instance_id: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly release_data: {
                  readonly dataType: 'pg/jsonb';
                  readonly codecId: 'pg/jsonb@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly section_id: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly sort_order: {
                  readonly dataType: 'pg/int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                  readonly many: false;
                };
                readonly user_id: {
                  readonly dataType: 'pg/int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly many: false;
                };
              };
              primaryKey: {
                readonly columns: readonly ['user_id', 'crate_id', 'instance_id'];
                readonly name: 'crate_releases_pkey';
              };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'crate_releases_added_at_idx';
                  readonly columns: readonly ['added_at'];
                  readonly unique: false;
                },
                {
                  readonly name: 'crate_releases_user_id_crate_id_added_at_idx';
                  readonly columns: readonly ['user_id', 'crate_id', 'added_at'];
                  readonly unique: false;
                },
                {
                  readonly name: 'crate_releases_user_id_crate_id_idx';
                  readonly columns: readonly ['user_id', 'crate_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'crate_releases_user_id_crate_id_sort_order_idx';
                  readonly columns: readonly ['user_id', 'crate_id', 'sort_order'];
                  readonly unique: false;
                },
                {
                  readonly name: 'crate_releases_user_id_instance_id_idx';
                  readonly columns: readonly ['user_id', 'instance_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'crate_releases';
                    readonly columns: readonly ['user_id', 'crate_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'crates';
                    readonly columns: readonly ['user_id', 'id'];
                  };
                  readonly name: 'crate_releases_user_id_crate_id_fkey';
                },
              ];
            };
            readonly crate_set_markers: {
              columns: {
                readonly accent_key: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly crate_id: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly created_at: {
                  readonly dataType: 'pg/timestamp';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                  readonly many: false;
                };
                readonly id: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly label: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly parent_id: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly sort_order: {
                  readonly dataType: 'pg/int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly updated_at: {
                  readonly dataType: 'pg/timestamp';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 3 };
                  readonly many: false;
                };
                readonly user_id: {
                  readonly dataType: 'pg/int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly many: false;
                };
              };
              primaryKey: {
                readonly columns: readonly ['user_id', 'crate_id', 'id'];
                readonly name: 'crate_set_markers_pkey';
              };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'crate_set_markers_user_id_crate_id_sort_order_idx';
                  readonly columns: readonly ['user_id', 'crate_id', 'sort_order'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'crate_set_markers';
                    readonly columns: readonly ['user_id', 'crate_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'crates';
                    readonly columns: readonly ['user_id', 'id'];
                  };
                  readonly name: 'crate_set_markers_user_id_crate_id_fkey';
                },
              ];
            };
            readonly crates: {
              columns: {
                readonly created_at: {
                  readonly dataType: 'pg/timestamp';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                  readonly many: false;
                };
                readonly id: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly is_default: {
                  readonly dataType: 'pg/bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                  readonly many: false;
                };
                readonly name: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly notes: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly packed_enabled: {
                  readonly dataType: 'pg/bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                  readonly many: false;
                };
                readonly private: {
                  readonly dataType: 'pg/bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                  readonly many: false;
                };
                readonly updated_at: {
                  readonly dataType: 'pg/timestamp';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                  readonly many: false;
                };
                readonly user_id: {
                  readonly dataType: 'pg/int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly username: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                  readonly many: false;
                };
              };
              primaryKey: {
                readonly columns: readonly ['user_id', 'id'];
                readonly name: 'crates_pkey';
              };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'crates_id_private_idx';
                  readonly columns: readonly ['id', 'private'];
                  readonly unique: false;
                },
                {
                  readonly name: 'crates_user_id_idx';
                  readonly columns: readonly ['user_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'crates_user_id_is_default_idx';
                  readonly columns: readonly ['user_id', 'is_default'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'crates';
                    readonly columns: readonly ['user_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'users';
                    readonly columns: readonly ['discogs_user_id'];
                  };
                  readonly name: 'crates_user_id_fkey';
                },
              ];
            };
            readonly product_analytics_daily_rollups: {
              columns: {
                readonly date: {
                  readonly dataType: 'pg/date';
                  readonly codecId: 'pg/date-string@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly dimension_key: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly dimension_type: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly event_count: {
                  readonly dataType: 'pg/int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly many: false;
                };
              };
              primaryKey: {
                readonly columns: readonly ['date', 'dimension_type', 'dimension_key'];
                readonly name: 'product_analytics_daily_rollups_pkey';
              };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'product_analytics_daily_rollups_date_idx';
                  readonly columns: readonly ['date'];
                  readonly unique: false;
                },
                {
                  readonly name: 'product_analytics_daily_rollups_dimension_type_date_idx';
                  readonly columns: readonly ['dimension_type', 'date'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly product_analytics_events: {
              columns: {
                readonly action: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly category: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly created_at: {
                  readonly dataType: 'pg/timestamp';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                  readonly many: false;
                };
                readonly event: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly id: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly label: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly page_path: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly user_id: {
                  readonly dataType: 'pg/int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly value: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                  readonly many: false;
                };
              };
              primaryKey: {
                readonly columns: readonly ['id'];
                readonly name: 'product_analytics_events_pkey';
              };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'product_analytics_events_created_at_idx';
                  readonly columns: readonly ['created_at'];
                  readonly unique: false;
                },
                {
                  readonly name: 'product_analytics_events_event_created_at_idx';
                  readonly columns: readonly ['event', 'created_at'];
                  readonly unique: false;
                },
                {
                  readonly name: 'product_analytics_events_page_path_created_at_idx';
                  readonly columns: readonly ['page_path', 'created_at'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly user_tracks: {
              columns: {
                readonly artist: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly first_played_at: {
                  readonly dataType: 'pg/timestamp';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                  readonly many: false;
                };
                readonly instance_id: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly last_listened_at: {
                  readonly dataType: 'pg/timestamp';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly precision: 3 };
                  readonly many: false;
                };
                readonly last_played_at: {
                  readonly dataType: 'pg/timestamp';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly precision: 3 };
                  readonly many: false;
                };
                readonly listen_count: {
                  readonly dataType: 'pg/int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                  readonly many: false;
                };
                readonly play_count: {
                  readonly dataType: 'pg/int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                  readonly many: false;
                };
                readonly release_title: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly track_key: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly track_position: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly track_title: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly updated_at: {
                  readonly dataType: 'pg/timestamp';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 3 };
                  readonly many: false;
                };
                readonly user_id: {
                  readonly dataType: 'pg/int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly youtube_id: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                  readonly many: false;
                };
              };
              primaryKey: {
                readonly columns: readonly ['user_id', 'track_key'];
                readonly name: 'user_tracks_pkey';
              };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'user_tracks_user_id_idx_6c952402';
                  readonly prefix: 'user_tracks_user_id_idx';
                  readonly columns: readonly ['user_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'user_tracks_user_id_last_listened_at_idx';
                  readonly columns: readonly ['user_id', 'last_listened_at'];
                  readonly unique: false;
                },
                {
                  readonly name: 'user_tracks_user_id_last_played_at_idx';
                  readonly columns: readonly ['user_id', 'last_played_at'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user_tracks';
                    readonly columns: readonly ['user_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'users';
                    readonly columns: readonly ['discogs_user_id'];
                  };
                  readonly name: 'user_tracks_user_id_fkey';
                },
              ];
            };
            readonly users: {
              columns: {
                readonly created_at: {
                  readonly dataType: 'pg/timestamp';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                  readonly many: false;
                };
                readonly discogs_user_id: {
                  readonly dataType: 'pg/int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly last_seen_at: {
                  readonly dataType: 'pg/timestamp';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly precision: 3 };
                  readonly many: false;
                };
                readonly login_count: {
                  readonly dataType: 'pg/int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                  readonly many: false;
                };
                readonly preferences: {
                  readonly dataType: 'pg/jsonb';
                  readonly codecId: 'pg/jsonb@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: "'{}'::jsonb";
                  };
                  readonly many: false;
                };
                readonly support_toast_dismissed: {
                  readonly dataType: 'pg/bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                  readonly many: false;
                };
                readonly support_toast_pending: {
                  readonly dataType: 'pg/bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                  readonly many: false;
                };
                readonly updated_at: {
                  readonly dataType: 'pg/timestamp';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 3 };
                  readonly many: false;
                };
                readonly username: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
              };
              primaryKey: {
                readonly columns: readonly ['discogs_user_id'];
                readonly name: 'users_pkey';
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly _prisma_migrations: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'PrismaMigrations';
    };
    readonly crate_releases: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'CrateReleases';
    };
    readonly crate_set_markers: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'CrateSetMarkers';
    };
    readonly crates: { readonly namespace: 'public' & NamespaceId; readonly model: 'Crates' };
    readonly product_analytics_daily_rollups: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ProductAnalyticsDailyRollups';
    };
    readonly product_analytics_events: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ProductAnalyticsEvents';
    };
    readonly user_tracks: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'UserTracks';
    };
    readonly users: { readonly namespace: 'public' & NamespaceId; readonly model: 'Users' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly CrateReleases: {
            readonly fields: {
              readonly addedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly crateId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly foundAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly instanceId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly releaseData: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/jsonb@1' };
              };
              readonly sectionId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly sortOrder: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly crates: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Crates';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId', 'crateId'];
                  readonly targetFields: readonly ['userId', 'id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'crate_releases';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly addedAt: { readonly column: 'added_at' };
                readonly crateId: { readonly column: 'crate_id' };
                readonly foundAt: { readonly column: 'found_at' };
                readonly instanceId: { readonly column: 'instance_id' };
                readonly releaseData: { readonly column: 'release_data' };
                readonly sectionId: { readonly column: 'section_id' };
                readonly sortOrder: { readonly column: 'sort_order' };
                readonly userId: { readonly column: 'user_id' };
              };
            };
          };
          readonly Crates: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly isDefault: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly notes: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly packedEnabled: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly private: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly username: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly crateReleases: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'CrateReleases';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['userId', 'id'];
                  readonly targetFields: readonly ['userId', 'crateId'];
                };
              };
              readonly crateSetMarkers: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'CrateSetMarkers';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['userId', 'id'];
                  readonly targetFields: readonly ['userId', 'crateId'];
                };
              };
              readonly user: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Users';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['discogsUserId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'crates';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly createdAt: { readonly column: 'created_at' };
                readonly id: { readonly column: 'id' };
                readonly isDefault: { readonly column: 'is_default' };
                readonly name: { readonly column: 'name' };
                readonly notes: { readonly column: 'notes' };
                readonly packedEnabled: { readonly column: 'packed_enabled' };
                readonly private: { readonly column: 'private' };
                readonly updatedAt: { readonly column: 'updated_at' };
                readonly userId: { readonly column: 'user_id' };
                readonly username: { readonly column: 'username' };
              };
            };
          };
          readonly CrateSetMarkers: {
            readonly fields: {
              readonly accentKey: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly crateId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly label: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly parentId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly sortOrder: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly crates: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Crates';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId', 'crateId'];
                  readonly targetFields: readonly ['userId', 'id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'crate_set_markers';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly accentKey: { readonly column: 'accent_key' };
                readonly crateId: { readonly column: 'crate_id' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly id: { readonly column: 'id' };
                readonly label: { readonly column: 'label' };
                readonly parentId: { readonly column: 'parent_id' };
                readonly sortOrder: { readonly column: 'sort_order' };
                readonly updatedAt: { readonly column: 'updated_at' };
                readonly userId: { readonly column: 'user_id' };
              };
            };
          };
          readonly PrismaMigrations: {
            readonly fields: {
              readonly appliedStepsCount: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly checksum: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 64 };
                };
              };
              readonly finishedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly logs: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly migrationName: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
              readonly rolledBackAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly startedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: '_prisma_migrations';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly appliedStepsCount: { readonly column: 'applied_steps_count' };
                readonly checksum: { readonly column: 'checksum' };
                readonly finishedAt: { readonly column: 'finished_at' };
                readonly id: { readonly column: 'id' };
                readonly logs: { readonly column: 'logs' };
                readonly migrationName: { readonly column: 'migration_name' };
                readonly rolledBackAt: { readonly column: 'rolled_back_at' };
                readonly startedAt: { readonly column: 'started_at' };
              };
            };
          };
          readonly ProductAnalyticsDailyRollups: {
            readonly fields: {
              readonly date: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-string@1' };
              };
              readonly dimensionKey: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly dimensionType: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly eventCount: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'product_analytics_daily_rollups';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly date: { readonly column: 'date' };
                readonly dimensionKey: { readonly column: 'dimension_key' };
                readonly dimensionType: { readonly column: 'dimension_type' };
                readonly eventCount: { readonly column: 'event_count' };
              };
            };
          };
          readonly ProductAnalyticsEvents: {
            readonly fields: {
              readonly action: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly category: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly event: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly label: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly pagePath: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly userId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly value: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'product_analytics_events';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly action: { readonly column: 'action' };
                readonly category: { readonly column: 'category' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly event: { readonly column: 'event' };
                readonly id: { readonly column: 'id' };
                readonly label: { readonly column: 'label' };
                readonly pagePath: { readonly column: 'page_path' };
                readonly userId: { readonly column: 'user_id' };
                readonly value: { readonly column: 'value' };
              };
            };
          };
          readonly Users: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly discogsUserId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly lastSeenAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly loginCount: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly preferences: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/jsonb@1' };
              };
              readonly supportToastDismissed: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly supportToastPending: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly username: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly crates: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Crates';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['discogsUserId'];
                  readonly targetFields: readonly ['userId'];
                };
              };
              readonly userTracks: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'UserTracks';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['discogsUserId'];
                  readonly targetFields: readonly ['userId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'users';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly createdAt: { readonly column: 'created_at' };
                readonly discogsUserId: { readonly column: 'discogs_user_id' };
                readonly lastSeenAt: { readonly column: 'last_seen_at' };
                readonly loginCount: { readonly column: 'login_count' };
                readonly preferences: { readonly column: 'preferences' };
                readonly supportToastDismissed: { readonly column: 'support_toast_dismissed' };
                readonly supportToastPending: { readonly column: 'support_toast_pending' };
                readonly updatedAt: { readonly column: 'updated_at' };
                readonly username: { readonly column: 'username' };
              };
            };
          };
          readonly UserTracks: {
            readonly fields: {
              readonly artist: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly firstPlayedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly instanceId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly lastListenedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly lastPlayedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly listenCount: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly playCount: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly releaseTitle: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly trackKey: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly trackPosition: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly trackTitle: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly youtubeId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Users';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['discogsUserId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'user_tracks';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly artist: { readonly column: 'artist' };
                readonly firstPlayedAt: { readonly column: 'first_played_at' };
                readonly instanceId: { readonly column: 'instance_id' };
                readonly lastListenedAt: { readonly column: 'last_listened_at' };
                readonly lastPlayedAt: { readonly column: 'last_played_at' };
                readonly listenCount: { readonly column: 'listen_count' };
                readonly playCount: { readonly column: 'play_count' };
                readonly releaseTitle: { readonly column: 'release_title' };
                readonly trackKey: { readonly column: 'track_key' };
                readonly trackPosition: { readonly column: 'track_position' };
                readonly trackTitle: { readonly column: 'track_title' };
                readonly updatedAt: { readonly column: 'updated_at' };
                readonly userId: { readonly column: 'user_id' };
                readonly youtubeId: { readonly column: 'youtube_id' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly forKeyShare: true;
      readonly forNoKeyUpdate: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly forShare: true;
      readonly forUpdate: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly lateral: true;
      readonly lockNowait: true;
      readonly lockOf: true;
      readonly lockSkipLocked: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
